package com.xm.foxy.dao;

import org.springframework.stereotype.Component;

import com.xm.foxy.model.Log;

@Component("logMapper")
public interface LogMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_log
	 * 
	 * @mbggenerated Tue Mar 08 00:36:16 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_log
	 * 
	 * @mbggenerated Tue Mar 08 00:36:16 CST 2016
	 */
	int insert(Log record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_log
	 * 
	 * @mbggenerated Tue Mar 08 00:36:16 CST 2016
	 */
	int insertSelective(Log record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_log
	 * 
	 * @mbggenerated Tue Mar 08 00:36:16 CST 2016
	 */
	Log selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_log
	 * 
	 * @mbggenerated Tue Mar 08 00:36:16 CST 2016
	 */
	int updateByPrimaryKeySelective(Log record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table t_log
	 * 
	 * @mbggenerated Tue Mar 08 00:36:16 CST 2016
	 */
	int updateByPrimaryKey(Log record);
}