package com.xm.foxy.dao;

import java.util.List;

import org.springframework.stereotype.Component;

import com.xm.foxy.model.User;

@Component("userMapper")
public interface UserMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Tue Mar 08 00:36:03 CST 2016
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Tue Mar 08 00:36:03 CST 2016
	 */
	int insert(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Tue Mar 08 00:36:03 CST 2016
	 */
	int insertSelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Tue Mar 08 00:36:03 CST 2016
	 */
	User selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Tue Mar 08 00:36:03 CST 2016
	 */
	int updateByPrimaryKeySelective(User record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table t_user
	 * @mbggenerated  Tue Mar 08 00:36:03 CST 2016
	 */
	int updateByPrimaryKey(User record);

	User findUserByName(String userName);

	List<User> findAll();

	void insertBatch(List<User> users);
}