package com.xm.foxy.model;

import java.io.Serializable;

public class User implements Serializable {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.id
	 * 
	 * @mbggenerated Tue Mar 08 00:36:03 CST 2016
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.userName
	 * 
	 * @mbggenerated Tue Mar 08 00:36:03 CST 2016
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.password
	 * 
	 * @mbggenerated Tue Mar 08 00:36:03 CST 2016
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column t_user.age
	 * 
	 * @mbggenerated Tue Mar 08 00:36:03 CST 2016
	 */
	private Integer age;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.id
	 * 
	 * @return the value of t_user.id
	 * @mbggenerated Tue Mar 08 00:36:03 CST 2016
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.id
	 * 
	 * @param id
	 *            the value for t_user.id
	 * @mbggenerated Tue Mar 08 00:36:03 CST 2016
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.userName
	 * 
	 * @return the value of t_user.userName
	 * @mbggenerated Tue Mar 08 00:36:03 CST 2016
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.userName
	 * 
	 * @param userName
	 *            the value for t_user.userName
	 * @mbggenerated Tue Mar 08 00:36:03 CST 2016
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.password
	 * 
	 * @return the value of t_user.password
	 * @mbggenerated Tue Mar 08 00:36:03 CST 2016
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.password
	 * 
	 * @param password
	 *            the value for t_user.password
	 * @mbggenerated Tue Mar 08 00:36:03 CST 2016
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column t_user.age
	 * 
	 * @return the value of t_user.age
	 * @mbggenerated Tue Mar 08 00:36:03 CST 2016
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column t_user.age
	 * 
	 * @param age
	 *            the value for t_user.age
	 * @mbggenerated Tue Mar 08 00:36:03 CST 2016
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	@Override
	public String toString() {
		return "User [id=" + id + ", userName=" + userName + ", password=" + password + ", age=" + age + "]";
	}

}